cdef extern from "floats.h" namespace "fmath":
    float ceil(float)
    float exp2(float)
    float floor(float)
    float log2(float)
    float neg(float)
    float newton_raphson(float, float)
    float pow(float, float)
    float round(float)
    float roundp(float, float)
    float rsqrt(float)
    float rsqrt_lomont(float)
    float rsqrt_quake(float)
    float sqrt(float)